backend:
  name: git-gateway
  branch: main
media_folder: /static/media
public_folder: /media
publish_mode: editorial_workflow
collections:
  - name: "Minutes"
    label: "Minutes (T1 2025)"
    folder: "content/minutes/t1-2025"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
