backend:
  name: git-gateway
  branch: main
media_folder: /static/media
public_folder: /media

collections:
  - name: "Minutes"
    label: "Minutes"
    folder: "content/minutes"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
